name: BGA-gel
markdown: kramdown

# ** uncomment and add subdirectory to render to github pages
# collections:
#   subdirname:
#     output: true

topnav:
  - title: Home
    url: "#"
  - title: Settings
    url: "#"
  - title: Profile
    url: "#"
  - title: Help
    url: "#"
sidemenu:
  - title: Home
    url: "#"
  - title: Option 2
    url: "#"
  - title: Option 3
    url: "#"
sidemenuactive: Home
